### PR TITLE
Add Cancel/Reset buttons #845

### PR DESCRIPTION
**Pull request by ICalofir**
I fixed the issue #845.

### CODE REVIEW

**Comment by palcu** [comment]
@iulianR what do you think about this?

**Comment by ICalofir** [comment]
I fixed the issue #832, but when I commited the files they automatically were added here :( (I wanted to make a new pull request but it didn't work). Anyway, @palcu can you review the lasts commits?

**Comment by gabrielivascu** [comment]
@ICalofir There are some commits here that don't match the issue you referenced. You should split this into two separate pull requests, one for issue #845 and one for the other thing that you've worked on.

As for the form buttons, please discard that `<input>` and only use `<button>` for consistency (I forgot to mention this in the issue description). Do this for all the forms you changed (see the form in [add_question.html] (https://github.com/rosedu/wouso/blob/master/wouso/resources/templates/cpanel/add_question.html) for example).

Also, you need to add buttons for the forms in `Add Tag` and `Edit Tag` pages too.

**Comment by ICalofir** [comment]
@gabrielivascu ok, I'll change those files. And yes, I know that there are some commits that don't match the issue. I didn't know that if I work on branch master they will update the new commits here. I will close this pull request and I will create new request, then everything should be ok.

**Comment by iulianR** [comment]
@ICalofir It's best you create one branch for every issue you fix. That way you can easily work on multiple issues at once while waiting for your pull requests to be reviewed/merged. When you want to update a pull request, you just switch to the corresponding branch and push new commits there.

Also, try to squash multiple commits that do the the same thing/have the same message into one.

**Pull request closed without merging**
