### PR TITLE
Fixed: pep8 linter => core folder

### PR DESCRIPTION
**Pull request by PopAdi**
Use pep8 linter on all Python files and fix errors and warnings #724 => done for the "core" folder

### CODE REVIEW

**Comment by PopAdi** [comment]
@palcu 
There are just indentation edits based on pep8 convention. I reviewed all of them again but I don't know why Travis CI build failed (however, codeclimate is ok).

**Comment by PopAdi** [comment]
@palcu or @mariuscoto 
I just indented the code from all the files in the core folder based on the pep8 conventions. If it's ok, I'll do it for the rest of them.

**Comment by iulianR** [comment]
@palcu @razvanch Do you think it's a good idea to alter most of the files in this way?

**Comment by razvanch** [comment]
@iulianR in my opinion this is a good change. It's a bit tedious to review a commit modifying 45 files, but all modifications seem right. It'd be quite a lot of spam if this would be broken into smaller commits.

**Comment by iulianR** [comment]
@PopAdi You should squash these 3 commits into one before we merge this. We don't want 3 commits with the same name, doing the same thing. :)

**Comment by PopAdi** [comment]
@iulianR I squashed the last 3 commits into one as you requested :)

**Comment by iulianR** [comment]
I noticed that you also ran pep8 on the `migrations` directory. Those are generated automatically by `south` and we should just ignore them.

Also, are you sure all the files inside the `core` directory have been checked?

**Comment by PopAdi** [comment]
Photo => http://i.imgur.com/gdalm5a.png
Yeah, all the files where checked and as I said, I ignored the "line too long" warnings, because they are false-positives, you can't always write a command in less than 80 characters. The ones remaining are also false-positives in my opinion. From 200+ warnings (original code) now there are just 9.

**Comment by iulianR** [comment]
@PopAdi Ok. Then remove the files in the migrations directory, update the pull request and I will merge this.

**Pull request closed without merging**
