### PR TITLE
Fix #873

### LINKED ISSUE #873: New install of WoUSO does not show cpanel/questions
Foarte foarte dubios...

### PR DESCRIPTION
**Pull request by palcu**
Fix #873 

Please code review @iulianR and @razvanch.

Wanted to show how to debug for a friend and solved this bug.

### CODE REVIEW

**Comment by palcu** [comment]
Btw. Does anybody have a fucking idea what `qpool` is and why do we need categories for it?

**Comment by palcu** [comment]
Wait. It's not working properly. I've found some fixtures that were been used before.

**Comment by palcu** [comment]
It's now done.

**Comment by iulianR** [comment]
+1 from me. You can merge if all good @razvanch.

**Pull request merged**
