### PR TITLE
Fixes in lesson

### PR DESCRIPTION
**Pull request by razvand**
Two fixes in the lesson module:
* Remove ending slash when including JavaScript file.
* Replace old `lesson_set()` function with `get_unordered_list()`.

### CODE REVIEW

**Comment by iulianR** [comment]
@gabrielivascu Have a look. I'm not sure how you used that method/property for ordering but is getting unnecessarily complicated. Also it's name is the same as the related name and that is really confusing.

**Comment by razvand** [comment]
@iulianR, the current implementation of the `lessons()` method is my doing. Initial it had issues, not considering all lessons. That was my fix, going again through the entire list of lessons.

**Comment by iulianR** [comment]
I'm merging it as it is and I will open an issue.

**Comment by gabrielivascu** [comment]
@razvand I don't see how that could happen. That ordering considers lessons id's which are unique.

**Comment by razvand** [comment]
If I did an ordering first and then added new lessons something nasty happened. I can't remembder, unfortunatelly. But it had to do with sorting lessons in categories, then adding lessons in categories and trying to sort them again.

**Pull request merged**
