### PR TITLE
Install libssl-dev package when installing wouso

### PR DESCRIPTION
**Pull request by razvand**
Mention this in the README.md file.

### CODE REVIEW

**Comment by sigkill** [comment]
Have kibssl-dev installed on raspian and still have this issue

**Comment by razvand** [comment]
@sigkill , be sure to make a fresh installation of wouso: clone, sandbox, pip install etc.

**Comment by sigkill** [comment]
Actually scratch that - after verification of libssl-dev I went ahead and re-ran the pip install -r requirements-extra step, then checked my mysql db settings, updated the password and things seem to be okay.

**Comment by razvand** [comment]
@sigkill, excellent. Glad it's working!

**Pull request merged**
