### PR TITLE
Make a shell script to automatically do the install steps

### PR DESCRIPTION
**Pull request by palcu**
# Need

```gherkin
As a mentor at ROSEdu CDL/Challenge
I lose valuable time with setting up the project steps
When I could automate this
```

# Deliverables

- [x] shell script that does the steps in `README.md`

### CODE REVIEW

**Comment by palcu** [comment]
Please take a look @iulianR.

**Comment by gabrielivascu** [comment]
@palcu  <code>apt-get</code> will not work on distributions like Fedora, openSUSE etc. I think it should be noted that this script will serve only for Debian/Ubuntu/Mint.

**Comment by iulianR** [comment]
@gabrielivascu We will update the README accordingly.
@palcu Looks good. We will merge this after we fix #663

**Comment by iulianR** [comment]
I forgot to merge this after README update -_-

**Pull request merged**
