### PR TITLE
No help pop-up for the CHALLENGE and REPORT buttons

### PR DESCRIPTION
**Pull request by andreibotila**
Issue #608

### CODE REVIEW

**Comment by iulianR** [comment]
@andreibotila You should add help text for the Report button as well and also fix the failing test.

**Comment by andreibotila** [comment]
@iulianR The Report button has the right pop-up unless i'm mistaking the button.

**Comment by iulianR** [comment]
@andreibotila You're right. Just fix the test then :)

**Comment by andreibotila** [comment]
@iulianR The Travis-CI was failing because internal test was using the old name "Challenge!" and not the new one "Challenge". I modified it and everything is ok.

**Pull request merged**
